<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uml2rdbms" nsURI="urn:uml2rdbms.ecore" nsPrefix="uml2rdbms">
  <eClassifiers xsi:type="ecore:EClass" name="PackageToSchema">
    <eStructuralFeatures xsi:type="ecore:EReference" name="p">
      <eType xsi:type="ecore:EClass" href="SimpleUML.ecore#//UmlPackage"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="s">
      <eType xsi:type="ecore:EClass" href="SimpleRDBMS.ecore#//RdbmsSchema"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pn">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassToTable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="c">
      <eType xsi:type="ecore:EClass" href="SimpleUML.ecore#//UmlClass"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t">
      <eType xsi:type="ecore:EClass" href="SimpleRDBMS.ecore#//RdbmsTable"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cn">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="p">
      <eType xsi:type="ecore:EClass" href="SimpleUML.ecore#//UmlPackage"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="s">
      <eType xsi:type="ecore:EClass" href="SimpleRDBMS.ecore#//RdbmsSchema"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cl">
      <eType xsi:type="ecore:EClass" href="SimpleRDBMS.ecore#//RdbmsColumn"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="k">
      <eType xsi:type="ecore:EClass" href="SimpleRDBMS.ecore#//RdbmsKey"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassToPkey">
    <eStructuralFeatures xsi:type="ecore:EReference" name="c">
      <eType xsi:type="ecore:EClass" href="SimpleUML.ecore#//UmlClass"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="k">
      <eType xsi:type="ecore:EClass" href="SimpleRDBMS.ecore#//RdbmsKey"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cn">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeToColumn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="c">
      <eType xsi:type="ecore:EClass" href="SimpleUML.ecore#//UmlClass"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t">
      <eType xsi:type="ecore:EClass" href="SimpleRDBMS.ecore#//RdbmsTable"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveAttributeToColumn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="c">
      <eType xsi:type="ecore:EClass" href="SimpleUML.ecore#//UmlClass"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t">
      <eType xsi:type="ecore:EClass" href="SimpleRDBMS.ecore#//RdbmsTable"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="an">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pn">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cn">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sqltype">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="a">
      <eType xsi:type="ecore:EClass" href="SimpleUML.ecore#//UmlAttribute"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="p">
      <eType xsi:type="ecore:EClass" href="SimpleUML.ecore#//UmlPrimitiveDataType"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cl">
      <eType xsi:type="ecore:EClass" href="SimpleRDBMS.ecore#//RdbmsColumn"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexAttributeToColumn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="c">
      <eType xsi:type="ecore:EClass" href="SimpleUML.ecore#//UmlClass"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t">
      <eType xsi:type="ecore:EClass" href="SimpleRDBMS.ecore#//RdbmsTable"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="an">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newPrefix">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="a">
      <eType xsi:type="ecore:EClass" href="SimpleUML.ecore#//UmlAttribute"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tc">
      <eType xsi:type="ecore:EClass" href="SimpleUML.ecore#//UmlClass"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuperAttributeToColumn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="c">
      <eType xsi:type="ecore:EClass" href="SimpleUML.ecore#//UmlClass"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="t">
      <eType xsi:type="ecore:EClass" href="SimpleRDBMS.ecore#//RdbmsTable"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sc">
      <eType xsi:type="ecore:EClass" href="SimpleUML.ecore#//UmlClass"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssocToFKey">
    <eStructuralFeatures xsi:type="ecore:EReference" name="a">
      <eType xsi:type="ecore:EClass" href="SimpleUML.ecore#//UmlAssociation"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fk">
      <eType xsi:type="ecore:EClass" href="SimpleRDBMS.ecore#//RdbmsForeignKey"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="an">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scn">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dcn">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fkn">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fcn">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="p">
      <eType xsi:type="ecore:EClass" href="SimpleUML.ecore#//UmlPackage"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sc">
      <eType xsi:type="ecore:EClass" href="SimpleUML.ecore#//UmlClass"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dc">
      <eType xsi:type="ecore:EClass" href="SimpleUML.ecore#//UmlClass"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="srcTbl">
      <eType xsi:type="ecore:EClass" href="SimpleRDBMS.ecore#//RdbmsTable"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="s">
      <eType xsi:type="ecore:EClass" href="SimpleRDBMS.ecore#//RdbmsSchema"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fc">
      <eType xsi:type="ecore:EClass" href="SimpleRDBMS.ecore#//RdbmsColumn"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pKey">
      <eType xsi:type="ecore:EClass" href="SimpleRDBMS.ecore#//RdbmsKey"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destTbl">
      <eType xsi:type="ecore:EClass" href="SimpleRDBMS.ecore#//RdbmsTable"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
